// Generated from src/routes/layout.css (baseline values from docs/research/color.md §2.1). Keep in sync.

/** The 49 md.sys.color roles in kebab-case (CSS var: --md-sys-color-<role>). */
export const COLOR_ROLES = [
	'primary',
	'on-primary',
	'primary-container',
	'on-primary-container',
	'primary-fixed',
	'primary-fixed-dim',
	'on-primary-fixed',
	'on-primary-fixed-variant',
	'inverse-primary',
	'secondary',
	'on-secondary',
	'secondary-container',
	'on-secondary-container',
	'secondary-fixed',
	'secondary-fixed-dim',
	'on-secondary-fixed',
	'on-secondary-fixed-variant',
	'tertiary',
	'on-tertiary',
	'tertiary-container',
	'on-tertiary-container',
	'tertiary-fixed',
	'tertiary-fixed-dim',
	'on-tertiary-fixed',
	'on-tertiary-fixed-variant',
	'error',
	'on-error',
	'error-container',
	'on-error-container',
	'surface',
	'surface-dim',
	'surface-bright',
	'surface-container-lowest',
	'surface-container-low',
	'surface-container',
	'surface-container-high',
	'surface-container-highest',
	'on-surface',
	'surface-variant',
	'on-surface-variant',
	'outline',
	'outline-variant',
	'inverse-surface',
	'inverse-on-surface',
	'scrim',
	'shadow',
	'surface-tint',
	'background',
	'on-background'
] as const;

export type ColorRole = (typeof COLOR_ROLES)[number];

/** kebab-case role -> MaterialDynamicColors method name (camelCase). */
export const roleToCamel = (role: ColorRole): string => role.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());

/** CSS custom property for a role, e.g. cssVar('primary') === '--md-sys-color-primary'. */
export const cssVar = (role: ColorRole) => `--md-sys-color-${role}` as const;

export type ColorMap = Record<ColorRole, string>;

/** M3 baseline light scheme (hand-curated, seed #6750A4). */
export const BASELINE_LIGHT: ColorMap = {
	'primary': '#6750a4',
	'on-primary': '#ffffff',
	'primary-container': '#eaddff',
	'on-primary-container': '#4f378b',
	'primary-fixed': '#eaddff',
	'primary-fixed-dim': '#d0bcff',
	'on-primary-fixed': '#21005d',
	'on-primary-fixed-variant': '#4f378b',
	'inverse-primary': '#d0bcff',
	'secondary': '#625b71',
	'on-secondary': '#ffffff',
	'secondary-container': '#e8def8',
	'on-secondary-container': '#4a4458',
	'secondary-fixed': '#e8def8',
	'secondary-fixed-dim': '#ccc2dc',
	'on-secondary-fixed': '#1d192b',
	'on-secondary-fixed-variant': '#4a4458',
	'tertiary': '#7d5260',
	'on-tertiary': '#ffffff',
	'tertiary-container': '#ffd8e4',
	'on-tertiary-container': '#633b48',
	'tertiary-fixed': '#ffd8e4',
	'tertiary-fixed-dim': '#efb8c8',
	'on-tertiary-fixed': '#31111d',
	'on-tertiary-fixed-variant': '#633b48',
	'error': '#b3261e',
	'on-error': '#ffffff',
	'error-container': '#f9dedc',
	'on-error-container': '#8c1d18',
	'surface': '#fef7ff',
	'surface-dim': '#ded8e1',
	'surface-bright': '#fef7ff',
	'surface-container-lowest': '#ffffff',
	'surface-container-low': '#f7f2fa',
	'surface-container': '#f3edf7',
	'surface-container-high': '#ece6f0',
	'surface-container-highest': '#e6e0e9',
	'on-surface': '#1d1b20',
	'surface-variant': '#e7e0ec',
	'on-surface-variant': '#49454f',
	'outline': '#79747e',
	'outline-variant': '#cac4d0',
	'inverse-surface': '#322f35',
	'inverse-on-surface': '#f5eff7',
	'scrim': '#000000',
	'shadow': '#000000',
	'surface-tint': '#6750a4',
	'background': '#fef7ff',
	'on-background': '#1d1b20'
};

/** M3 baseline dark scheme. */
export const BASELINE_DARK: ColorMap = {
	'primary': '#d0bcff',
	'on-primary': '#381e72',
	'primary-container': '#4f378b',
	'on-primary-container': '#eaddff',
	'primary-fixed': '#eaddff',
	'primary-fixed-dim': '#d0bcff',
	'on-primary-fixed': '#21005d',
	'on-primary-fixed-variant': '#4f378b',
	'inverse-primary': '#6750a4',
	'secondary': '#ccc2dc',
	'on-secondary': '#332d41',
	'secondary-container': '#4a4458',
	'on-secondary-container': '#e8def8',
	'secondary-fixed': '#e8def8',
	'secondary-fixed-dim': '#ccc2dc',
	'on-secondary-fixed': '#1d192b',
	'on-secondary-fixed-variant': '#4a4458',
	'tertiary': '#efb8c8',
	'on-tertiary': '#492532',
	'tertiary-container': '#633b48',
	'on-tertiary-container': '#ffd8e4',
	'tertiary-fixed': '#ffd8e4',
	'tertiary-fixed-dim': '#efb8c8',
	'on-tertiary-fixed': '#31111d',
	'on-tertiary-fixed-variant': '#633b48',
	'error': '#f2b8b5',
	'on-error': '#601410',
	'error-container': '#8c1d18',
	'on-error-container': '#f9dedc',
	'surface': '#141218',
	'surface-dim': '#141218',
	'surface-bright': '#3b383e',
	'surface-container-lowest': '#0f0d13',
	'surface-container-low': '#1d1b20',
	'surface-container': '#211f26',
	'surface-container-high': '#2b2930',
	'surface-container-highest': '#36343b',
	'on-surface': '#e6e0e9',
	'surface-variant': '#49454f',
	'on-surface-variant': '#cac4d0',
	'outline': '#938f99',
	'outline-variant': '#49454f',
	'inverse-surface': '#e6e0e9',
	'inverse-on-surface': '#322f35',
	'scrim': '#000000',
	'shadow': '#000000',
	'surface-tint': '#d0bcff',
	'background': '#141218',
	'on-background': '#e6e0e9'
};
